<?php

namespace Database\Seeders;

use App\Models\Warehouse;
use Illuminate\Database\Seeder;

class WarehouseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $warehouses = [
            [
                'code'      => 'NDX-JKT-01',
                'name'      => 'NDX Hub DC Jakarta Pusat',
                'city'      => 'Jakarta Pusat',
                'province'  => 'DKI Jakarta',
                'address'   => 'Jl. Medan Merdeka Barat No. 12, Gambir, Jakarta Pusat',
                'lat'       => -6.1805,
                'lng'       => 106.8284,
                'phone'     => '021-34567890',
                'pic_name'  => 'Budi Santoso',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-JKT-02',
                'name'      => 'NDX Hub DC Jakarta Selatan',
                'city'      => 'Jakarta Selatan',
                'province'  => 'DKI Jakarta',
                'address'   => 'Jl. TB Simatupang No. 88, Cilandak, Jakarta Selatan',
                'lat'       => -6.2615,
                'lng'       => 106.8106,
                'phone'     => '021-78901234',
                'pic_name'  => 'Agus Prasetyo',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-JKT-03',
                'name'      => 'NDX Hub DC Jakarta Timur',
                'city'      => 'Jakarta Timur',
                'province'  => 'DKI Jakarta',
                'address'   => 'Jl. Raya Bogor KM 22, Ciracas, Jakarta Timur',
                'lat'       => -6.2251,
                'lng'       => 106.9004,
                'phone'     => '021-87654321',
                'pic_name'  => 'Rian Firmansyah',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-BDG-01',
                'name'      => 'NDX Hub DC Bandung',
                'city'      => 'Bandung',
                'province'  => 'Jawa Barat',
                'address'   => 'Jl. Soekarno Hatta No. 450, Batununggal, Bandung',
                'lat'       => -6.9175,
                'lng'       => 107.6191,
                'phone'     => '022-7561234',
                'pic_name'  => 'Dadan Ramdani',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-SBY-01',
                'name'      => 'NDX Hub DC Surabaya',
                'city'      => 'Surabaya',
                'province'  => 'Jawa Timur',
                'address'   => 'Jl. Rungkut Industri Raya No. 15, Rungkut, Surabaya',
                'lat'       => -7.2575,
                'lng'       => 112.7521,
                'phone'     => '031-8439001',
                'pic_name'  => 'Eko Wahyudi',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-YOG-01',
                'name'      => 'NDX Hub DC Yogyakarta',
                'city'      => 'Yogyakarta',
                'province'  => 'DI Yogyakarta',
                'address'   => 'Jl. Ringroad Utara No. 99, Sleman, Yogyakarta',
                'lat'       => -7.7956,
                'lng'       => 110.3695,
                'phone'     => '0274-567890',
                'pic_name'  => 'Joko Susilo',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-SMG-01',
                'name'      => 'NDX Hub DC Semarang',
                'city'      => 'Semarang',
                'province'  => 'Jawa Tengah',
                'address'   => 'Kawasan Industri Candi Blok XI No. 8, Semarang',
                'lat'       => -6.9932,
                'lng'       => 110.4229,
                'phone'     => '024-7623456',
                'pic_name'  => 'Bambang Tri',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-MED-01',
                'name'      => 'NDX Hub DC Medan',
                'city'      => 'Medan',
                'province'  => 'Sumatera Utara',
                'address'   => 'Jl. Gatot Subroto KM 7.5, Medan Sunggal, Medan',
                'lat'       => 3.5952,
                'lng'       => 98.6722,
                'phone'     => '061-8456789',
                'pic_name'  => 'Zulham Siregar',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-PLG-01',
                'name'      => 'NDX Hub DC Palembang',
                'city'      => 'Palembang',
                'province'  => 'Sumatera Selatan',
                'address'   => 'Jl. Alamsyah Ratu Prawiranegara No. 25, Palembang',
                'lat'       => -2.9761,
                'lng'       => 104.7754,
                'phone'     => '0711-445566',
                'pic_name'  => 'Rahmat Hidayat',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-PKU-01',
                'name'      => 'NDX Hub DC Pekanbaru',
                'city'      => 'Pekanbaru',
                'province'  => 'Riau',
                'address'   => 'Jl. Soekarno Hatta No. 120, Payung Sekaki, Pekanbaru',
                'lat'       => 0.5071,
                'lng'       => 101.4478,
                'phone'     => '0761-589000',
                'pic_name'  => 'Hendra Wijaya',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-BLI-01',
                'name'      => 'NDX Hub DC Denpasar (Bali)',
                'city'      => 'Denpasar',
                'province'  => 'Bali',
                'address'   => 'Jl. By Pass Ngurah Rai No. 88X, Sanur, Denpasar',
                'lat'       => -8.6705,
                'lng'       => 115.2126,
                'phone'     => '0361-289001',
                'pic_name'  => 'Wayan Sudarma',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-MKS-01',
                'name'      => 'NDX Hub DC Makassar',
                'city'      => 'Makassar',
                'province'  => 'Sulawesi Selatan',
                'address'   => 'Kawasan Pergudangan Parangloe Indah Blok F No. 3, Makassar',
                'lat'       => -5.1477,
                'lng'       => 119.4327,
                'phone'     => '0411-512345',
                'pic_name'  => 'Andi Syarifuddin',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-BPN-01',
                'name'      => 'NDX Hub DC Balikpapan',
                'city'      => 'Balikpapan',
                'province'  => 'Kalimantan Timur',
                'address'   => 'Jl. Mulawarman KM 13, Manggar, Balikpapan',
                'lat'       => -1.2654,
                'lng'       => 116.8312,
                'phone'     => '0542-765432',
                'pic_name'  => 'Surya Pratama',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-BTM-01',
                'name'      => 'NDX Hub DC Batam',
                'city'      => 'Batam',
                'province'  => 'Kepulauan Riau',
                'address'   => 'Komp. Industri Batamindo Blok C No. 10, Mukakuning, Batam',
                'lat'       => 1.1301,
                'lng'       => 104.0529,
                'phone'     => '0778-612345',
                'pic_name'  => 'Tommy Kurniawan',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-TNG-01',
                'name'      => 'NDX Hub DC Tangerang',
                'city'      => 'Tangerang',
                'province'  => 'Banten',
                'address'   => 'Jl. Raya Daan Mogot KM 20, Batuceper, Tangerang',
                'lat'       => -6.1781,
                'lng'       => 106.6297,
                'phone'     => '021-55667788',
                'pic_name'  => 'Faisal Akbar',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-BEK-01',
                'name'      => 'NDX Hub DC Bekasi',
                'city'      => 'Bekasi',
                'province'  => 'Jawa Barat',
                'address'   => 'Jl. Raya Narogong KM 7, Rawalumbu, Bekasi',
                'lat'       => -6.2349,
                'lng'       => 107.0004,
                'phone'     => '021-88990011',
                'pic_name'  => 'Dimas Saputra',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-DPK-01',
                'name'      => 'NDX Hub DC Depok',
                'city'      => 'Depok',
                'province'  => 'Jawa Barat',
                'address'   => 'Jl. Raya Margonda No. 350, Beji, Depok',
                'lat'       => -6.4025,
                'lng'       => 106.7942,
                'phone'     => '021-77889900',
                'pic_name'  => 'Arief Nugroho',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-BOR-01',
                'name'      => 'NDX Hub DC Bogor',
                'city'      => 'Bogor',
                'province'  => 'Jawa Barat',
                'address'   => 'Jl. Raya Pajajaran No. 125, Baranangsiang, Bogor',
                'lat'       => -6.5971,
                'lng'       => 106.7960,
                'phone'     => '0251-8345678',
                'pic_name'  => 'Yusuf Maulana',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-MLG-01',
                'name'      => 'NDX Hub DC Malang',
                'city'      => 'Malang',
                'province'  => 'Jawa Timur',
                'address'   => 'Jl. Kolonel Sugiono No. 200, Sukun, Malang',
                'lat'       => -7.9797,
                'lng'       => 112.6304,
                'phone'     => '0341-356789',
                'pic_name'  => 'Bayu Anggoro',
                'is_active' => true,
            ],
            [
                'code'      => 'NDX-PTK-01',
                'name'      => 'NDX Hub DC Pontianak',
                'city'      => 'Pontianak',
                'province'  => 'Kalimantan Barat',
                'address'   => 'Jl. Kom Yos Sudarso No. 80, Jeruju, Pontianak Barat',
                'lat'       => -0.0263,
                'lng'       => 109.3425,
                'phone'     => '0561-734567',
                'pic_name'  => 'Ferry Hermawan',
                'is_active' => true,
            ],
        ];

        foreach ($warehouses as $data) {
            Warehouse::updateOrCreate(
                ['code' => $data['code']],
                $data
            );
        }
    }
}
